### ISSUE TITLE
How to filter with tags

### ISSUE THREAD

**Issue by olivej** [tamber/tamber-node#1]
We do not understand how to filter with tags.  With properties, they have a value, but tags are just a name without a value.  If we wanted to filter out certain items that were tagged a certain way, say we had movies and we wanted to filter out movies tagged as "horror".  How would we do this?  Is there some kind of "exists" keyword?
Any advice appreciated.

**Comment by argusdusty** [comment]
Hi there,
Filtering on tags is a new feature just released a few hours ago, and I'm afraid our docs haven't been updated to reflect this yet.
"tags" is an operator that takes no arguments (that is, an empty list), so an item's tags can be referenced in a filter with `{"tags": []}`.
We also have new operators, "contains" and "overlaps" as part of the same release, which act on arrays (such as tags). "contains" returns whether or not the first argument contains all elements in the second. "overlaps" returns whether or not the first arguments contains any of the elements in the second.

So, if you want a filter to remove movies tagged as "horror", you could use `{"not": [{"contains": [{"tags": []}, ["horror"]]}]}`
`{"not": [{"contains": [{"tags": []}, "horror"]}]}` will also work, since the "contains" operator treats non-array literals as a single-element array.

**Comment by olivej** [comment]
This is great info, thank you for the clarity. We look forward to trying this out soon.
